[package]
name = "connection"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.27", features = ["derive"] }
confy = "0.5.1"
dns-lookup = "1.0.8"
inquire = "0.5.2"
serde = { version = "1.0.148", features = ["derive"] }
socket2 = "0.4.7"
