[package]
name = "connection"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.27", features = ["derive"] }
confy = "0.5.1"
dns-lookup = "1.0.8"
inquire = "0.5.2"
serde = { version = "1.0.148", features = ["derive"] }
socket2 = "0.4.7"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
